### ISSUE TITLE
Where can I get access to the TED talks dataset used in this practical ?

### ISSUE THREAD

**Issue by napsternxg** [oxford-cs-deepnlp-2017/practical-2#3]
I would like to use the TED talk dataset for research purposes. What will be a good place to access the data. Also are there any related publications which use this data?

**Comment by bshillingford** [comment]
Data's available here: https://wit3.fbk.eu/

Try google scholar for papers that use it:
https://scholar.google.com/scholar?cites=12776906165170856443&as_sdt=2005&sciodt=0,5&hl=en

(It's not in this practical because the first practical's IPython notebook
has the URLs: https://github.com/oxford-cs-deepnlp-2017/practical1)

**Comment by napsternxg** [comment]
Wow. Thanks for the links.
